;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.CameraShake",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dead",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Katana",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Knockdown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Dead",DevComment="")
+GameplayTagList=(Tag="MyTags.Weapon.Knife",DevComment="")

